#!/bin/sh

echo "Welcome"

PYCMD=$(cat <<EOF
from bs4 import BeautifulSoup
from urllib.request import Request, urlopen
import re
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--name',type=str,required=True)
args = parser.parse_args()

bruh=open("links.txt","w")

req = Request(args.name)
html_page = urlopen(req)

soup = BeautifulSoup(html_page, "lxml")

links = []
for link in soup.findAll('a'):
    links.append(link.get('href'))

links2=[]
for i in links:
    lex = i.find("i.4cdn.org")
    if lex > -1:
        fuckthisshit=i[2:]
        links2.append(fuckthisshit)

seggs = "no"

for k in links2:
    if k != seggs:
        bruh.write(k+"\n")
        seggs = k
EOF
)


read -p "Do you want to sync to a thread?(default "No"): <[y]es> " sync

if [[ $sync == "y" ]]
then
    read -p "Enter directory to sync to: " direc

    if [[ -d "$HOME/Downloads/4chan-stuff/$direc" ]]
    then
        echo "$direc exists"
        echo "Syncing..."
        cd $HOME/Downloads/4chan-stuff/$direc
        var1="$HOME/Downloads/4chan-stuff/$direc/threadid.txt"
        var2=$(cat "$var1")
        python3 -c "$PYCMD" --name $var2

    else
        echo "$direc doesn't exist"
    fi
else
    read -p "Enter thread url: " thread_url
    read -p "Enter directory name: " direc
    echo "Creating a new directory in $HOME/Downloads/4chan-stuff..."
    echo "Files will be saved in $HOME/Downloads/4chan-stuff/$direc"
    cd $HOME/Downloads/4chan-stuff/
    mkdir $direc
    cd $direc
    python3 -c "$PYCMD" --name $thread_url
    touch threadid.txt
    threadid="$HOME/Downloads/4chan-stuff/$direc/threadid.txt"
    echo "$thread_url" > "$threadid"
fi


if [[ ! -f $HOME/Downloads/4chan-stuff/$direc/links.txt ]]
then
    echo "ERROR: links.txt does not exist."
else
    wget -nc -i links.txt
    rm links.txt
fi
