#!/bin/sh
read -p "Enter thread url: " thread_url
read -p "Enter folder name: " direc
echo "Files will be saved in $HOME/Downloads/$direc"
cd $HOME/Downloads/
mkdir $direc
cd $direc

PYCMD=$(cat <<EOF
from bs4 import BeautifulSoup
from urllib.request import Request, urlopen
import re
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--name',type=str,required=True)
args = parser.parse_args()

bruh=open("links.txt","w")

req = Request(args.name)
html_page = urlopen(req)

soup = BeautifulSoup(html_page, "lxml")

links = []
for link in soup.findAll('a'):
    links.append(link.get('href'))

links2=[]
for i in links:
    lex = i.find("i.4cdn.org")
    if lex > -1:
        fuckthisshit=i[2:]
        links2.append(fuckthisshit)

seggs = "no"

for k in links2:
    if k != seggs:
        bruh.write(k+"\n")
        seggs = k
EOF
)

python3 -c "$PYCMD" --name $thread_url

if [[ ! -f $HOME/Downloads/$direc/links.txt ]]
then
    echo "ERROR: links.txt does not exist."
else
    wget -i links.txt
    rm links.txt
fi
